name: Code Formatter

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  date:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repository
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Format code
        run: deno fmt

      - name: Setup git configuration
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit changes
        run: |
          git add .
          git commit -m "style: apply formatting fixes"
          git push origin main
