name: Publish on JSR

on:
  release:
    types: [created]
    branches: ['main']

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Publish package
        uses: actions/checkout@v4
        run: deno publish
